### ISSUE TITLE
Backend Loading/Timing Issue with an inline Module.  

### ISSUE THREAD

**Issue by eibiflo** [maikschneider/bw_focuspoint_images#22]
I discovered the extension and really love the concept. I'm still using TYPO3 11, and I've noticed that the editor only fully loads 6-8 times out of 10 attempts. The other times, something goes wrong with the initial loading, and all the points are at X:0 at the top.

I also don't get any JavaScript errors, and if I disable my cache in the console, it works again on the next load, but I can't expect an editor to require this workaround. 
Is this problem already known? Is there a better workaround?

Not Success: 
![image](https://github.com/maikschneider/bw_focuspoint_images/assets/75035727/67e6b92f-1f1e-400d-8a26-d7020d37944e)
Success:
![image](https://github.com/maikschneider/bw_focuspoint_images/assets/75035727/208163c3-29cc-4e3d-b473-8901d556e479)

**Comment by maikschneider** [comment]
Ah yes, I remember the issue. When having the problem, a small resize of the browser instantly fixes the boxes. I guess it has something to do with the event binding of the Modal. The problem was gone when switching to ES6 in v12.
I'm not sure if I'll have a deeper look into it.. Maybe a dirty setTimeout that triggers the resize event would be sufficient

**Comment by maikschneider** [comment]
Uh, I would always recommend to create a fork and configure it to run in your installation. This way, you can easily make adjustments and create a pull requests. When it's merged, you can drop your fork. 
Thanks for looking into it, good luck!
